require ("utils/table")

WeaponHash = {
    dagger = "",
    bat = "",
    bottle = "",
    crowbar = "",
    unarmed = "",
    flashlight = "",
    golfclub = "",
    hammer = "",
    hatchet = "",
    knuckle = "",
    knife = "",
    machete = "",
    switchblade = "",
    nightstick = "",
    wrench = "",
    battleaxe = "",
    poolcue = "",
    stone_hatchet = "",
    pistol = "",
    pistol_mk2 = "",
    combatpistol = "",
    appistol = "",
    stungun = "",
    pistol50 = "",
    snspistol = "",
    snspistol_mk2 = "",
    heavypistol = "",
    vintagepistol = "",
    flaregun = "",
    marksmanpistol = "",
    revolver = "",
    revolver_mk2 = "",
    doubleaction = "",
    raypistol = "",
    ceramicpistol = "",
    navyrevolver = "",
    microsmg = "",
    smg = "",
    smg_mk2 = "",
    assaultsmg = "",
    combatpdw = "",
    machinepistol = "",
    minismg = "",
    raycarbine = "",
    pumpshotgun = "",
    pumpshotgun_mk2 = "",
    sawnoffshotgun = "",
    assaultshotgun = "",
    bullpupshotgun = "",
    musket = "",
    heavyshotgun = "",
    dbshotgun = "",
    autoshotgun = "",
    assaultrifle = "",
    assaultrifle_mk2 = "",
    carbinerifle = "",
    carbinerifle_mk2 = "",
    advancedrifle = "",
    specialcarbine = "",
    specialcarbine_mk2 = "",
    bullpuprifle = "",
    bullpuprifle_mk2 = "",
    compactrifle = "",
    mg = "",
    combatmg = "",
    combatmg_mk2 = "",
    gusenberg = "",
    sniperrifle = "",
    heavysniper = "",
    heavysniper_mk2 = "",
    marksmanrifle = "",
    marksmanrifle_mk2 = "",
    rpg = "",
    grenadelauncher = "",
    grenadelauncher_smoke = "",
    minigun = "",
    firework = "",
    railgun = "",
    hominglauncher = "",
    compactlauncher = "",
    rayminigun = "",
    grenade = "",
    bzgas = "",
    smokegrenade = "",
    flare = "",
    molotov = "",
    stickybomb = "",
    proxmine = "",
    snowball = "",
    pipebomb = "",
    ball = "",
    petrolcan = "",
    fireextinguisher = "",
    parachute = "",
    hazardcan = ""
}
WeaponHashName = table_invert(WeaponHash)

WeaponPickups = {"pickup_weapon_advancedrifle", "pickup_weapon_appistol", "pickup_weapon_assaultrifle", "pickup_weapon_assaultrifle_mk2",
"pickup_weapon_assaultshotgun", "pickup_weapon_assaultsmg", "pickup_weapon_autoshotgun", "pickup_weapon_ball", "pickup_weapon_bat",
"pickup_weapon_battleaxe", "pickup_weapon_bottle", "pickup_weapon_bullpuprifle", "pickup_weapon_bullpuprifle_mk2", "pickup_weapon_bullpupshotgun",
"pickup_weapon_bzgas", "pickup_weapon_carbinerifle", "pickup_weapon_carbinerifle_mk2", "pickup_weapon_combatmg", "pickup_weapon_combatmg_mk2",
"pickup_weapon_combatpdw", "pickup_weapon_combatpistol", "pickup_weapon_compactlauncher", "pickup_weapon_compactrifle", "pickup_weapon_crowbar",
"pickup_weapon_dagger", "pickup_weapon_dbshotgun", "pickup_weapon_doubleaction", "pickup_weapon_fireextinguisher", "pickup_weapon_firework",
"pickup_weapon_flare", "pickup_weapon_flaregun", "pickup_weapon_flashlight", "pickup_weapon_golfclub", "pickup_weapon_grenade", "pickup_weapon_grenadelauncher",
"pickup_weapon_gusenberg", "pickup_weapon_hammer", "pickup_weapon_hatchet", "pickup_weapon_heavypistol", "pickup_weapon_heavyshotgun", "pickup_weapon_heavysniper",
"pickup_weapon_heavysniper_mk2", "pickup_weapon_hominglauncher", "pickup_weapon_knife", "pickup_weapon_knuckle", "pickup_weapon_machete", "pickup_weapon_machinepistol",
"pickup_weapon_marksmanpistol", "pickup_weapon_marksmanrifle", "pickup_weapon_marksmanrifle_mk2", "pickup_weapon_mg", "pickup_weapon_microsmg", "pickup_weapon_minigun",
"pickup_weapon_minismg", "pickup_weapon_molotov", "pickup_weapon_musket", "pickup_weapon_nightstick", "pickup_weapon_petrolcan", "pickup_weapon_pipebomb",
"pickup_weapon_pistol", "pickup_weapon_pistol50", "pickup_weapon_pistol_mk2", "pickup_weapon_poolcue", "pickup_weapon_proxmine", "pickup_weapon_pumpshotgun",
"pickup_weapon_pumpshotgun_mk2", "pickup_weapon_railgun", "pickup_weapon_raycarbine", "pickup_weapon_rayminigun", "pickup_weapon_raypistol", "pickup_weapon_revolver",
"pickup_weapon_revolver_mk2", "pickup_weapon_rpg", "pickup_weapon_sawnoffshotgun", "pickup_weapon_smg", "pickup_weapon_smg_mk2", "pickup_weapon_smokegrenade",
"pickup_weapon_sniperrifle", "pickup_weapon_snowball", "pickup_weapon_snspistol", "pickup_weapon_snspistol_mk2", "pickup_weapon_specialcarbine",
"pickup_weapon_specialcarbine_mk2", "pickup_weapon_stickybomb", "pickup_weapon_stone_hatchet", "pickup_weapon_stungun", "pickup_weapon_switchblade",
"pickup_weapon_vintagepistol", "pickup_weapon_wrench"}