local Sx=1						--default Male/Female 1/2

local GTr=2671447+59			--v1.60 Trigger
local GHs=2671447+46			--v1.60 PedHash
local CrVO=2725269				--Create Vehicle Offset



local function getDelay()
	delay, incr=0, 0.01 globals.set_int(GTr, 1)
	while (true) do delay=delay+incr sleep(incr) if globals.get_int(GTr)==0 then return delay+incr end end
end

local function set_model_hash(h)
	OlCrV=globals.get_int(CrVO+27+66) LpC=0 d=getDelay()
	while h~=0 do menu.send_key_press(156)
		if globals.get_int(CrVO+27+66)~=h and LpC<10 then globals.set_int(GTr, 1)
			if h then globals.set_int(GHs, h) end		--Unusual Menu error prevention
			sleep(d) globals.set_int(GTr, 0) globals.set_int(GHs, 0) LpC=LpC+1 end
		if globals.get_int(CrVO+27+66)==h or LpC==10 then globals.set_int(CrVO+27+66, OlCrV) return end sleep(0.1)
	end
end

local ShpShft=menu.add_submenu("ShapeShift")


local MP,ANM,CosP,BRD,SCRe,FCHarSt,MCHarSt,FChar,MChar,FCutS,MCutS,FGang,MGang,LAW,Other={},{},{},{},{},{},{},{},{},{},{},{},{},{},{}
local Birdy,Sea,FemSt,mSt,FeC,MaC,FCu,MCu,FGn,MGn,Law,Oth,Ani,Cos

MP[joaat("mp_m_freemode_01")]="MP Male" MP[joaat("mp_f_freemode_01")]="MP Female"
 
ANM[joaat("a_c_boar")]="Boar"			ANM[joaat("a_c_cat_01")]="Cat"				ANM[joaat("a_c_chimp")]="Chimp"			ANM[joaat("a_c_chop")]="Chop"
ANM[joaat("a_c_chop_02")]="Chop2" 		ANM[joaat("a_c_cow")]="Cow" 				ANM[joaat("a_c_coyote")]="Coyote" 		ANM[joaat("a_c_deer")]="Deer"
ANM[joaat("a_c_husky")]="Husky" 		ANM[joaat("a_c_mtlion")]="Mountain Lion"	ANM[joaat("a_c_panther")]="Panther"		ANM[joaat("a_c_pig")]="Pig"
ANM[joaat("a_c_poodle")]="Poodle" 		ANM[joaat("a_c_pug")]="Pug" 				ANM[joaat("a_c_rabbit_01")]="Rabbit"	ANM[joaat("a_c_rat")]="Rat"
ANM[joaat("a_c_retriever")]="Retriever" ANM[joaat("a_c_rottweiler")]="Rottweiler"	ANM[joaat("a_c_shepherd")]="Shepherd"	ANM[joaat("a_c_rhesus")]="Rhesus"
ANM[joaat("a_c_westy")]="Westy"

CosP[joaat("s_m_y_clown_01")]="Clown"			CosP[joaat("u_m_y_imporage")]="ImpoRage"		CosP[joaat("u_m_m_jesus_01")]="Jesus01"		
CosP[joaat("s_m_m_movalien_01")]="MovAlien"		CosP[joaat("s_m_m_movspace_01")]="MovSpace"		CosP[joaat("u_m_y_pogo_01")]="Pogo"
CosP[joaat("ig_priest")]="Priest"				CosP[joaat("u_m_y_rsranger_01")]="RsRanger"		CosP[joaat("u_m_y_zombie_01")]="Zombie"
CosP[joaat("ig_johnnyklebitz")]="JohnnyKlebitz"	CosP[joaat("s_m_y_mime")]="Mime"				CosP[joaat("ig_orleans")]="Orleans" -- ----
CosP[joaat("u_m_y_juggernaut_01")]="juggernaut" CosP[joaat("u_m_y_corpse_01")]="corpse"

BRD[joaat("a_c_chickenhawk")]="ChickenHawk"		BRD[joaat("a_c_cormorant")]="Comorant-swan like"	BRD[joaat("a_c_crow")]="Crow"
BRD[joaat("a_c_hen")]="Hen"						BRD[joaat("a_c_pigeon")]="Pigeon"					BRD[joaat("a_c_seagull")]="Seagull"

SCRe[joaat("a_c_dolphin")]="Dolphin"	SCRe[joaat("a_c_fish")]="Fish"						SCRe[joaat("a_c_whalegrey")]="GreyWhale"
SCRe[joaat("a_c_humpback")]="Humpback"	SCRe[joaat("a_c_sharkhammer")]="HammerHead Shark"	SCRe[joaat("a_c_killerwhale")]="KillerWhale"
SCRe[joaat("a_c_stingray")]="Sting Ray"	SCRe[joaat("a_c_sharktiger")]="Tiger Shark"

FCHarSt[joaat("ig_agatha")]="Agatha"					FCHarSt[joaat("ig_amandatownley")]="AmandaTownley"		FCHarSt[joaat("ig_denise")]="Denise"
FCHarSt[joaat("csb_denise_friend")]="DeniseFriendCS" 	FCHarSt[joaat("ig_georginacheng")]="GeorginaCheng"		FCHarSt[joaat("ig_imani")]="Imani"
FCHarSt[joaat("ig_maryann")]="Maryann" 					FCHarSt[joaat("ig_mimi")]="Mimi"						FCHarSt[joaat("ig_mrsphillips")]="MrsPhillips"
FCHarSt[joaat("ig_paige")]="Paige"						FCHarSt[joaat("a_m_m_prolhost_01")]="PrologueHostage01"	FCHarSt[joaat("a_f_m_prolhost_01")]="PrologueHostage01AFM"
FCHarSt[joaat("ig_sessanta")]="Sessanta"				FCHarSt[joaat("ig_tanisha")]="Tanisha"					FCHarSt[joaat("ig_tonya")]="Tonya"
FCHarSt[joaat("ig_tracydisanto")]="TracyDisanto"

MCHarSt[joaat("ig_mp_agent14")]="Agent14"					MCHarSt[joaat("ig_ary")]="Ary" 							MCHarSt[joaat("ig_ary_02")]="Ary2"
MCHarSt[joaat("ig_avischwartzman_02")]="AviSchwartzman"		MCHarSt[joaat("ig_avon")]="Avon"						MCHarSt[joaat("ig_barry")]="Barry"
MCHarSt[joaat("ig_billionaire")]="Billionaire"				MCHarSt[joaat("ig_brad")]="Brad"						MCHarSt[joaat("ig_davenorton")]="DaveNorton"
MCHarSt[joaat("ig_devin")]="Devin"							MCHarSt[joaat("s_m_y_devinsec_01")]="DevinSec01SMY"		MCHarSt[joaat("ig_dom")]="Dom"
MCHarSt[joaat("ig_drfriedlander")]="DrFriedlander"			MCHarSt[joaat("u_m_m_edtoh")]="EdToh"					MCHarSt[joaat("ig_englishdave")]="EnglishDave"
MCHarSt[joaat("ig_englishdave_02")]="EnglishDave2"			MCHarSt[joaat("ig_fabien")]="Fabien"					MCHarSt[joaat("ig_floyd")]="Floyd"
MCHarSt[joaat("ig_floyd")]="Gustavo"						MCHarSt[joaat("player_one")]="Franklin"					MCHarSt[joaat("p_franklin_02")]="FranklinNew"
MCHarSt[joaat("hc_hacker")]="Hacker"						MCHarSt[joaat("ig_hao")]="Hao"							MCHarSt[joaat("ig_jay_norris")]="JayNorris"
MCHarSt[joaat("ig_jimmydisanto")]="JimmyDisanto"			MCHarSt[joaat("ig_jimmydisanto2")]="JimmyDisanto2"		MCHarSt[joaat("ig_lamardavis")]="LamarDavis"
MCHarSt[joaat("ig_lazlow")]="Lazlow"						MCHarSt[joaat("ig_lazlow_2")]="Lazlow2"					MCHarSt[joaat("ig_lestercrest")]="LesterCrest1"
MCHarSt[joaat("ig_lestercrest_2")]="LesterCrest2"			MCHarSt[joaat("ig_lestercrest_3")]="LesterCrest3"		MCHarSt[joaat("ig_lifeinvad_01")]="LifeInvad01"
MCHarSt[joaat("s_m_m_lifeinvad_01")]="LifeInvad01SMM"		MCHarSt[joaat("ig_lifeinvad_02")]="LifeInvad02"			MCHarSt[joaat("ig_lildee")]="Lildee"
MCHarSt[joaat("cs_martinmadrazo")]="MartinMadrazoCutscene"	MCHarSt[joaat("ig_miguelmadrazo")]="MiguelMadrazo"		MCHarSt[joaat("player_zero")]="MichaelTownley"
MCHarSt[joaat("ig_moodyman_02")]="Moodyman"					MCHarSt[joaat("ig_mrk")]="MrK"							MCHarSt[joaat("ig_nervousron")]="NervousRon"
MCHarSt[joaat("ig_nigel")]="Nigel"							MCHarSt[joaat("mp_m_niko_01")]="Niko01"					MCHarSt[joaat("ig_rashcosvki")]="Rashkovsky"
MCHarSt[joaat("ig_helmsmanpavel")]="Pavel"					MCHarSt[joaat("u_m_y_proldriver_01")]="PrologueDriver"	MCHarSt[joaat("a_m_m_prolhost_01")]="PrologueHostage01AMM"
MCHarSt[joaat("u_m_m_promourn_01")]="PrologueMournMale01"	MCHarSt[joaat("u_m_m_prolsec_01")]="PrologueSec01"		MCHarSt[joaat("csb_prolsec")]="PrologueSec01Cutscene"
MCHarSt[joaat("ig_prolsec_02")]="PrologueSec02"				MCHarSt[joaat("u_f_o_prolhost_01")]="PrologueHostage01"	MCHarSt[joaat("ig_siemonyetarian")]="SiemonYetarian"
MCHarSt[joaat("ig_sol")]="Sol"								MCHarSt[joaat("ig_solomon")]="Solomon"					MCHarSt[joaat("ig_stevehains")]="SteveHain"
MCHarSt[joaat("ig_stretch")]="Stretch"						MCHarSt[joaat("ig_taocheng")]="TaoCheng"				MCHarSt[joaat("ig_taocheng2")]="TaoCheng2"
MCHarSt[joaat("ig_taostranslator")]="TaosTranslator"		MCHarSt[joaat("ig_taostranslator2")]="TaosTranslator2"	MCHarSt[joaat("ig_tomcasino")]="TomCasino"
MCHarSt[joaat("ig_tonyprince")]="TonyPrince"				MCHarSt[joaat("player_two")]="Trevor"					MCHarSt[joaat("ig_vincent")]="Vincent"
MCHarSt[joaat("ig_vincent_2")]="Vincent2"					MCHarSt[joaat("ig_vincent_3")]="Vincent3"				MCHarSt[joaat("ig_wade")]="Wade"

FChar[joaat("s_f_m_autoshop_01")]="Autoshop"				FChar[joaat("ig_abigail")]="Abigail"					FChar[joaat("ig_ashley")]="Ashley"
FChar[joaat("s_f_y_airhostess_01")]="AirHostess01SFY"		FChar[joaat("s_f_y_bartender_01")]="Bartender01SFY"		FChar[joaat("s_f_y_baywatch_01")]="BayWatch01SFY"
FChar[joaat("a_f_m_beach_01")]="Beach01AFM"					FChar[joaat("a_f_y_beach_01")]="Beach01AFY"				FChar[joaat("a_f_y_beach_02")]="Beach02AFY"
FChar[joaat("s_f_y_beachbarstaff_01")]="Beachbarstaff_01"	FChar[joaat("u_f_y_beth")]="Beth"						FChar[joaat("mp_f_bennymech_01")]="BennyMP"
FChar[joaat("a_f_m_bevhills_01")]="BevHills01"				FChar[joaat("a_f_m_bevhills_02")]="BevHills02"			FChar[joaat("a_f_y_bevhills_01")]="BevHills1"
FChar[joaat("a_f_y_bevhills_02")]="Bevhills2"				FChar[joaat("a_f_y_bevhills_03")]="BevHills3"			FChar[joaat("a_f_y_bevhills_04")]="BevHills4"
FChar[joaat("a_f_y_bevhills_05")]="BevHills5"				FChar[joaat("u_f_y_bikerchic")]="BikerChic"				FChar[joaat("mp_f_boatstaff_01")]="BoatStaff01F"
FChar[joaat("a_f_m_bodybuild_01")]="BodyBuilder"			FChar[joaat("ig_bride")]="Bride"						FChar[joaat("a_f_y_business_01")]="Business01AFY"
FChar[joaat("a_f_m_business_02")]="Business02AFM"			FChar[joaat("a_f_y_business_02")]="Business02AFY"		FChar[joaat("a_f_y_business_03")]="Business03AFY"
FChar[joaat("a_f_y_business_04")]="Business04AFY"			FChar[joaat("u_f_o_carol")]="Carol"						FChar[joaat("mp_f_cardesign_01")]="CarDesign"
FChar[joaat("a_f_y_carclub_01")]="CarClub"					FChar[joaat("u_f_m_casinocash_01")]="CasinoCash"		FChar[joaat("u_f_m_casinoshop_01")]="CasinoShop"
FChar[joaat("s_f_y_casino_01")]="ClubCasino"				FChar[joaat("s_f_y_clubbar_01")]="ClubBar"				FChar[joaat("s_f_y_clubbar_02")]="ClubBar2"
FChar[joaat("mp_f_chbar_01")]="ClubBarMP"					FChar[joaat("a_f_y_clubcust_01")]="Clubcust01"			FChar[joaat("a_f_y_clubcust_02")]="Clubcust02"
FChar[joaat("a_f_y_clubcust_03")]="Clubcust03"				FChar[joaat("a_f_y_clubcust_04")]="Clubcust04"			FChar[joaat("u_f_y_comjane")]="ComJane"
FChar[joaat("mp_f_cocaine_01")]="Cocaine"					FChar[joaat("u_f_m_corpse_01")]="CorpseUFM01"			FChar[joaat("u_f_y_corpse_01")]="CorpseUFY1"
FChar[joaat("u_f_y_corpse_02")]="CorpseUFY2"				FChar[joaat("mp_f_counterfeit_01")]="Counterfeit_01"	FChar[joaat("u_f_y_danceburl_01")]="DanceBurl"
FChar[joaat("u_f_y_dancelthr_01")]="DanceThr"				FChar[joaat("u_f_y_dancerave_01")]="DanceRave"			FChar[joaat("u_f_m_debbie_01")]="Debbie"
FChar[joaat("mp_f_deadhooker")]="Deadhooker"				FChar[joaat("u_f_m_drowned_01")]="Drowned"				FChar[joaat("a_f_m_eastsa_01")]="EastSA01AFM"
FChar[joaat("a_f_y_eastsa_01")]="EastSA01AFY"				FChar[joaat("a_f_m_eastsa_02")]="EastSA02AFM"			FChar[joaat("a_f_y_eastsa_02")]="EastSA02AFY"
FChar[joaat("a_f_y_eastsa_03")]="EastSA03AFY"				FChar[joaat("u_f_o_eileen")]="Eileen"					FChar[joaat("mp_f_execpa_01")]="ExecPA1"
FChar[joaat("mp_f_execpa_02")]="ExecPA2"					FChar[joaat("a_f_y_epsilon_01")]="Epsilon01AFY"			FChar[joaat("s_f_y_factory_01")]="Factory01SFY"
FChar[joaat("a_f_m_fatbla_01")]="FatBla01AFM"				FChar[joaat("a_f_m_fatcult_01")]="FatCult01AFM"			FChar[joaat("a_f_m_fatwhite_01")]="FatWhite01AFM"
FChar[joaat("s_f_m_fembarber")]="FemBarberSFM"				FChar[joaat("a_f_y_fitness_01")]="Fitness01AFY"			FChar[joaat("a_f_y_fitness_02")]="Fitness02AFY"
FChar[joaat("mp_f_forgery_01")]="Forgery"					FChar[joaat("a_f_y_genhot_01")]="GenHot01AFY"			FChar[joaat("a_f_o_genstreet_01")]="Genstreet01AFY"
FChar[joaat("a_f_y_gencaspat_01")]="Gencaspat01AFY"			FChar[joaat("a_f_y_golfer_01")]="Golfer01AFY"			FChar[joaat("cs_gurk")]="Gurk"
FChar[joaat("mp_f_helistaff_01")]="Heli Staff"				FChar[joaat("a_f_y_hiker_01")]="Hiker01AFY"				FChar[joaat("a_f_y_hippie_01")]="Hippie01AFY"
FChar[joaat("a_f_y_hipster_01")]="Hipster01AFY"				FChar[joaat("a_f_y_hipster_02")]="Hipster02AFY"			FChar[joaat("a_f_y_hipster_03")]="Hipster03AFY"
FChar[joaat("a_f_y_hipster_04")]="Hipster04AFY"				FChar[joaat("s_f_y_hooker_01")]="Hooker01SFY"			FChar[joaat("s_f_y_hooker_02")]="Hooker02SFY"
FChar[joaat("s_f_y_hooker_03")]="Hooker03SFY"				FChar[joaat("u_f_y_hotposh_01")]="HotPosh01"			FChar[joaat("g_f_importexport_01")]="ImportExport"
FChar[joaat("a_f_o_indian_01")]="Indian01AFO"				FChar[joaat("a_f_y_indian_01")]="Indian01AFY"			FChar[joaat("ig_jackie")]="Jacky"
FChar[joaat("ig_janet")]="Janet"							FChar[joaat("u_f_y_jewelass_01")]="JewelAss01"			FChar[joaat("ig_jewelass")]="JewelAss"
FChar[joaat("a_f_y_juggalo_01")]="Juggalo01AFY"				FChar[joaat("ig_karen_daniels")]="KarenDaniels"			FChar[joaat("ig_kaylee")]="Kaylee"
FChar[joaat("ig_kerrymcintosh")]="KerryMcintosh"			FChar[joaat("ig_kerrymcintosh_02")]="KerryMcintosh2"	FChar[joaat("a_f_m_ktown_01")]="KTown01AFM"
FChar[joaat("a_f_m_ktown_02")]="KTown02AFM"					FChar[joaat("a_f_o_ktown_01")]="KTown01AFO"				FChar[joaat("u_f_y_lauren")]="Lauren"
FChar[joaat("s_f_m_maid_01")]="Maid"						FChar[joaat("ig_magenta")]="Magenta"					FChar[joaat("s_f_m_maid_01")]="Maid01SFM"
FChar[joaat("ig_marnie")]="Marnie"							FChar[joaat("ig_maude")]="Maude"						FChar[joaat("mp_f_meth_01")]="Meth"
FChar[joaat("ig_michelle")]="Michelle"						FChar[joaat("s_f_y_migrant_01")]="Migrant01SFY"			FChar[joaat("u_f_y_mistress")]="Mistress"
FChar[joaat("u_f_m_miranda")]="Miranda"						FChar[joaat("u_f_m_miranda_02")]="Miranda2"				FChar[joaat("mp_f_misty_01")]="Misty01"
FChar[joaat("ig_molly")]="Molly"							FChar[joaat("u_f_o_moviestar")]="MovieStar"				FChar[joaat("s_f_y_movprem_01")]="MovPrem01SFY"
FChar[joaat("ig_mrs_thornhill")]="MrsThornhill"				FChar[joaat("ig_natalia")]="Natalia"					FChar[joaat("ig_patricia")]="Patricia"
FChar[joaat("ig_patricia_02")]="Patricia2"					FChar[joaat("u_f_y_poppymich")]="PoppyMich"				FChar[joaat("u_f_y_poppymich_02")]="PoppyMich2"
FChar[joaat("u_f_y_princess")]="Princess"					FChar[joaat("u_f_o_prolhost_01")]="PrologueHost1"		FChar[joaat("u_f_m_promourn_01")]="PrologueMourn1"
FChar[joaat("s_f_m_retailstaff_01")]="RetailStaff"			FChar[joaat("a_f_y_runner_01")]="Runner01AFY"			FChar[joaat("a_f_y_rurmeth_01")]="RurMeth01AFY"
FChar[joaat("a_f_m_salton_01")]="Salton01AFM"				FChar[joaat("a_f_o_salton_01")]="Salton01AFO"			FChar[joaat("ig_screen_writer")]="ScreenWriter"
FChar[joaat("s_f_y_scrubs_01")]="Scrubs"					FChar[joaat("a_f_y_scdressy_01")]="SCDressy01AFY"		FChar[joaat("s_f_m_shop_high")]="ShopHighSFM"
FChar[joaat("s_f_y_shop_low")]="ShopLowSFY"					FChar[joaat("s_f_y_shop_mid")]="ShopMidSFY"				FChar[joaat("a_f_y_skater_01")]="Skater01AFY"
FChar[joaat("a_f_m_skidrow_01")]="Skidrow01AFM"				FChar[joaat("a_f_y_smartcaspat_01")]="Smartcaspat01AFY"	FChar[joaat("a_f_m_soucent_01")]="SouCent01AFM"
FChar[joaat("a_f_m_soucent_02")]="SouCent02AFM"				FChar[joaat("a_f_o_soucent_01")]="SouCent01AFO"			FChar[joaat("a_f_y_soucent_01")]="SouCent01AFY"
FChar[joaat("a_f_o_soucent_02")]="SouCent02AFO"				FChar[joaat("a_f_y_soucent_02")]="SouCent02AFY"			FChar[joaat("a_f_y_soucent_03")]="SouCent03AFY"
FChar[joaat("a_f_m_soucentmc_01")]="SouCentMC01AFM"			FChar[joaat("u_f_y_spyactress")]="SpyActress"			FChar[joaat("s_f_y_stripper_01")]="Stripper01SFY"
FChar[joaat("s_f_y_stripper_02")]="Stripper02SFY"			FChar[joaat("s_f_y_stripperlite")]="StripperLite"		FChar[joaat("mp_f_stripperlite")]="StripperLiteMP"
FChar[joaat("s_f_m_studioassist_01")]="StudioAssistant"		FChar[joaat("a_f_y_studioparty_01")]="StudioParty1"		FChar[joaat("a_f_y_studioparty_02")]="StudioParty2"
FChar[joaat("s_f_m_sweatshop_01")]="SweatShop01SFM"			FChar[joaat("s_f_y_sweatshop_01")]="SweatShop01SFY"		FChar[joaat("ig_talina")]="Talina"
FChar[joaat("u_f_y_taylor")]="Taylor"						FChar[joaat("a_f_y_tennis_01")]="Tennis01AFY"			FChar[joaat("a_f_y_topless_01")]="Topless01AFY"
FChar[joaat("a_f_m_tourist_01")]="Tourist01AFM"				FChar[joaat("a_f_y_tourist_01")]="Tourist01AFY"			FChar[joaat("a_f_y_tourist_02")]="Tourist02AFY"
FChar[joaat("a_f_m_trampbeac_01")]="Tramp01AFM"				FChar[joaat("a_f_m_tramp_01")]="TrampBeac01AFM"			FChar[joaat("a_m_m_tranvest_01")]="TranVest01AMM"
FChar[joaat("a_m_m_tranvest_02")]="TranVest02AMM"			FChar[joaat("a_f_y_vinewood_01")]="Vinewood01AFY"		FChar[joaat("a_f_y_vinewood_02")]="Vinewood02AFY"
FChar[joaat("a_f_y_vinewood_03")]="Vinewood03AFY"			FChar[joaat("a_f_y_vinewood_04")]="Vinewood04AFY"		FChar[joaat("mp_f_weed_01")]="Weed"
FChar[joaat("ig_wendy")]="Wendy"							FChar[joaat("a_f_y_yoga_01")]="Yoga01AFY"

MChar[joaat("ig_agent")]="Agent"							MChar[joaat("u_m_y_abner")]="Abner"						MChar[joaat("a_m_m_acult_01")]="Acult01AMM"
MChar[joaat("a_m_o_acult_01")]="Acult01AMO"					MChar[joaat("a_m_y_acult_01")]="Acult01AMY"				MChar[joaat("a_m_o_acult_02")]="Acult02AMO"
MChar[joaat("a_m_y_acult_02")]="Acult02AMY"					MChar[joaat("a_m_m_afriamer_01")]="AfriAmer01AMM"		MChar[joaat("s_m_y_airworker")]="AirWorkerSMY"
MChar[joaat("u_m_m_aldinapoli")]="AlDiNapoli"				MChar[joaat("s_m_y_ammucity_01")]="AmmuCity01SMY"		MChar[joaat("s_m_m_ammucountry")]="AmmuCountrySMM"
MChar[joaat("ig_andreas")]="Andreas"						MChar[joaat("u_m_y_antonb")]="AntonB"					MChar[joaat("s_m_y_autopsy_01")]="Autopsy01SMY"
MChar[joaat("s_m_m_autoshop_01")]="AutoShop01SMM"			MChar[joaat("s_m_m_autoshop_02")]="Autoshop02SMM"		MChar[joaat("s_m_m_autoshop_03")]="Autoshop03SMM"
MChar[joaat("ig_money")]="AviSchwartzman"					MChar[joaat("g_m_y_azteca_01")]="Azteca01GMY"			MChar[joaat("u_m_y_babyd")]="BabyD"
MChar[joaat("u_m_m_bankman")]="Bankman01"					MChar[joaat("ig_bankman")]="Bankman"					MChar[joaat("s_m_y_barman_01")]="Barman01SMY"
MChar[joaat("u_m_y_baygor")]="Baygor"						MChar[joaat("s_m_y_baywatch_01")]="BayWatch01SMY"		MChar[joaat("a_m_m_beach_02")]="Beach01AMM"
MChar[joaat("a_m_o_beach_01")]="Beach01AMO"					MChar[joaat("a_m_o_beach_02")]="Beach02AMO"				MChar[joaat("a_m_y_beach_01")]="Beach01AMY"
MChar[joaat("a_m_m_beach_02")]="Beach02AMM"					MChar[joaat("a_m_y_beach_02")]="Beach02AMY"				MChar[joaat("a_m_y_beach_03")]="Beach03AMY"
MChar[joaat("a_m_y_beach_04")]="Beach04AMY"					MChar[joaat("a_m_y_beachvesp_01")]="BeachVesp01AMY"		MChar[joaat("a_m_y_beachvesp_02")]="Beachvesp02AMY"
MChar[joaat("ig_benny")]="Benny"							MChar[joaat("ig_benny_02")]="Benny2"					MChar[joaat("ig_bestmen")]="BestMen"
MChar[joaat("ig_beverly")]="Beverly"						MChar[joaat("a_m_m_bevhills_01")]="BevHills01AMM"		MChar[joaat("a_m_y_bevhills_01")]="BevHills01AMY"
MChar[joaat("a_m_m_bevhills_02")]="BevHills02AMM"			MChar[joaat("a_m_y_bevhills_02")]="BevHills02AMY"		MChar[joaat("u_m_m_bikehire_01")]="BikeHire01"
MChar[joaat("mp_m_boatstaff_01")]="BoatStaff01M"			MChar[joaat("s_m_m_bouncer_01")]="Bouncer01SMM"			MChar[joaat("s_m_m_bouncer_02")]="Bouncer01SMM"
MChar[joaat("a_m_y_breakdance_01")]="BreakDance01AMY"		MChar[joaat("ig_brucie2")]="Brucie2"					MChar[joaat("u_m_y_burgerdrug_01")]="BurgerDrug"
MChar[joaat("s_m_y_busboy_01")]="BusBoy01SMY"				MChar[joaat("a_m_y_busicas_01")]="Busicas01AMY"			MChar[joaat("a_m_m_business_01")]="Business01AMM"
MChar[joaat("a_m_y_business_01")]="Business01AMY"			MChar[joaat("a_m_y_business_02")]="Business02AMY"		MChar[joaat("a_m_y_business_03")]="Business03AMY"
MChar[joaat("s_m_o_busker_01")]="Busker01SMO"				MChar[joaat("a_m_y_carclub_01")]="CarClub"				MChar[joaat("a_m_y_clubcust_01")]="CarClubCustomer"
MChar[joaat("a_m_y_clubcust_02")]="CarClubCustomer2"		MChar[joaat("a_m_y_clubcust_03")]="CarClubCustomer3"	MChar[joaat("a_m_y_clubcust_04")]="CarClubCustomer4"
MChar[joaat("ig_car3guy1")]="Car3Guy1"						MChar[joaat("ig_car3guy2")]="Car3Guy2"					MChar[joaat("s_m_m_ccrew_01")]="CCrew01SMM"
MChar[joaat("s_m_y_chef_01")]="Chef01SMY"					MChar[joaat("ig_celeb_01")]="Celeb1"					MChar[joaat("ig_chef2")]="Chef2"
MChar[joaat("ig_chef")]="Chef"								MChar[joaat("g_m_m_chemwork_01")]="ChemWork01GMM"		MChar[joaat("s_m_m_chemsec_01")]="ChemSec01SMM"
MChar[joaat("u_m_y_chip")]="Chip"							MChar[joaat("ig_chrisformage")]="ChrisFormage"			MChar[joaat("mp_m_claude_01")]="Claude01"
MChar[joaat("ig_clay")]="Clay"								MChar[joaat("ig_claypain")]="ClayPain"					MChar[joaat("ig_cletus")]="Cletus"
MChar[joaat("s_m_m_cntrybar_01")]="CntryBar01SMM"			MChar[joaat("s_m_y_construct_01")]="Construct01SMY"		MChar[joaat("s_m_y_construct_02")]="Construct02SMY"
MChar[joaat("ig_chrisformage")]="CrisFormage"				MChar[joaat("u_m_y_cyclist_01")]="Cyclist01"			MChar[joaat("a_m_y_cyclist_01")]="Cyclist01amy"
MChar[joaat("ig_dale")]="Dale"								MChar[joaat("s_m_y_dealer_01")]="Dealer01SMY"			MChar[joaat("u_m_o_dean")]="Dean"
MChar[joaat("a_m_y_dhill_01")]="DHill01AMY"					MChar[joaat("ig_djblamadon")]="DJBladamon"				MChar[joaat("ig_djblamrupert")]="DJBlamRupert"
MChar[joaat("ig_djblamryanh")]="DJBlamRyanh"				MChar[joaat("ig_djblamryans")]="DJBlamRyan"				MChar[joaat("ig_djdixmanager")]="DJDixManager"
MChar[joaat("ig_djgeneric_01")]="DJGeneric"					MChar[joaat("ig_djsolfotios")]="DJSolFotios"			MChar[joaat("ig_djsoljakob")]="DJSolJakob"
MChar[joaat("ig_djsolmanager")]="DJSolManager"				MChar[joaat("ig_djsolmike")]="DJSolMike"				MChar[joaat("ig_djsolrobt")]="DJSolRobot"
MChar[joaat("ig_djtalaurelia")]="DJtalaurelia"				MChar[joaat("ig_djtalignazio")]="DJtalignazio"			MChar[joaat("ig_isldj_00")]="DJ1"
MChar[joaat("ig_isldj_01")]="DJ2"							MChar[joaat("ig_isldj_02")]="DJ3"						MChar[joaat("ig_isldj_03")]="DJ4"
MChar[joaat("ig_isldj_04")]="DJ5"							MChar[joaat("ig_isldj_04_d_01")]="DJ11"					MChar[joaat("ig_isldj_04_d_02")]="DJ22"
MChar[joaat("ig_isldj_04_e_01")]="DJ33"						MChar[joaat("u_m_m_doa_01")]="DoaMan"					MChar[joaat("s_m_m_dockwork_01")]="DockWork01SMM"
MChar[joaat("s_m_y_dockwork_01")]="DockWork01SMY"			MChar[joaat("s_m_m_doctor_01")]="Doctor01SMM"			MChar[joaat("s_m_y_doorman_01")]="Doorman01SMY"
MChar[joaat("a_m_y_downtown_01")]="DownTown01AMY"			MChar[joaat("ig_dreyfuss")]="Dreyfuss"					MChar[joaat("ig_drugdealer")]="DrugDealer"
MChar[joaat("s_m_y_dwservice_01")]="DWService01SMY"			MChar[joaat("s_m_y_dwservice_02")]="DWService02SMY"		MChar[joaat("a_m_m_eastsa_01")]="EastSA01AMM"
MChar[joaat("a_m_y_eastsa_01")]="Eastsa01AMY"				MChar[joaat("a_m_m_eastsa_02")]="EastSa02AMM"			MChar[joaat("a_m_y_eastsa_02")]="EastSA02AMY"
MChar[joaat("ig_entourage_a")]="EntourageA"					MChar[joaat("ig_entourage_b")]="EntourageB"				MChar[joaat("a_m_y_epsilon_01")]="Epsilon01AMY"
MChar[joaat("a_m_y_epsilon_02")]="Epsilon02AMY"				MChar[joaat("s_m_y_factory_01")]="Factory01SMY"			MChar[joaat("g_m_y_famca_01")]="FamCA01GMY"
MChar[joaat("mp_m_famdd_01")]="FamDD01"						MChar[joaat("g_m_y_famdnf_01")]="FamDNF01GMY"			MChar[joaat("g_m_y_famfor_01")]="FamFor01GMY"
MChar[joaat("a_m_m_farmer_01")]="Farmer01AMM"				MChar[joaat("a_m_m_fatlatin_01")]="FatLatin01AMM"		MChar[joaat("u_m_m_filmdirector")]="FilmDirector"
MChar[joaat("u_m_o_filmnoir")]="FilmNoir"					MChar[joaat("u_m_o_finguru_01")]="FinGuru01"			MChar[joaat("s_m_y_fireman_01")]="Fireman01SMY"
MChar[joaat("ig_g")]="G"									MChar[joaat("s_m_m_gaffer_01")]="Gaffer01SMM"			MChar[joaat("s_m_y_garbage")]="GarbageSMY"
MChar[joaat("s_m_m_gardener_01")]="Gardener01SMM"			MChar[joaat("a_m_y_gay_01")]="Gay01AMY"					MChar[joaat("a_m_y_gay_02")]="Gay02AMY"
MChar[joaat("a_m_m_genfat_01")]="GenFat01AMM"				MChar[joaat("a_m_m_genfat_02")]="GenFat02AMM"			MChar[joaat("a_m_o_genstreet_01")]="GenStreet01AMO"
MChar[joaat("a_m_y_genstreet_01")]="GenStreet01AMY"			MChar[joaat("a_m_y_genstreet_02")]="GenStreet02AMY"		MChar[joaat("s_m_m_gentransport")]="GenTransportSMM"
MChar[joaat("u_m_m_glenstank_01")]="GlenStank01"			MChar[joaat("a_m_m_golfer_01")]="Golfer01AMM"			MChar[joaat("a_m_y_golfer_01")]="Golfer01AMY"
MChar[joaat("ig_golfer_a")]="GolferA"						MChar[joaat("ig_golfer_b")]="GolferB"					MChar[joaat("u_m_m_griff_01")]="Griff01"
MChar[joaat("s_m_y_grip_01")]="Grip01SMY"					MChar[joaat("ig_groom")]="Groom"						MChar[joaat("u_m_y_guido_01")]="Guido01"
MChar[joaat("u_m_y_gunvend_01")]="GunVend01"				MChar[joaat("s_m_m_hairdress_01")]="HairDress01SMM"		MChar[joaat("ig_hao")]="Hao"
MChar[joaat("ig_hao_02")]="Hao2"							MChar[joaat("a_m_m_hasjew_01")]="HasJew01AMM"			MChar[joaat("a_m_y_hasjew_01")]="HasJew01AMY"
MChar[joaat("a_m_y_hiker_01")]="Hiker01AMY"					MChar[joaat("a_m_m_hillbilly_01")]="HillBilly01AMM"		MChar[joaat("a_m_m_hillbilly_02")]="HillBilly02AMM"
MChar[joaat("a_m_y_hippy_01")]="Hippy01AMY"					MChar[joaat("u_m_y_hippie_01")]="Hippie01UMY"			MChar[joaat("a_m_y_hipster_01")]="Hipster01AMY"
MChar[joaat("a_m_y_hipster_02")]="Hipster02AMY"				MChar[joaat("a_m_y_hipster_03")]="Hipster03AMY"			MChar[joaat("ig_ramp_hipster")]="HipsterRamp"
MChar[joaat("hc_driver")]="HCDriver"						MChar[joaat("a_m_m_indian_01")]="Indian01AMM"			MChar[joaat("a_m_y_indian_01")]="Indian01AMY"
MChar[joaat("s_m_m_janitor")]="JanitorSMM"					MChar[joaat("a_m_y_jetski_01")]="JetSki01AMY"			MChar[joaat("u_m_m_jewelsec_01")]="JewelSec01"
MChar[joaat("u_m_m_jewelthief")]="JewelThief"				MChar[joaat("ig_jimmyboston")]="JimmyBoston"			MChar[joaat("ig_jimmyboston_02")]="JimmyBoston2"
MChar[joaat("ig_jio")]="Jio"								MChar[joaat("ig_jio_02")]="Jio2"						MChar[joaat("ig_joeminuteman")]="JoeMinuteman"
MChar[joaat("ig_johnnyklebitz")]="Johnnyklebitz"			MChar[joaat("ig_josef")]="Josef"						MChar[joaat("ig_josh")]="Josh"
MChar[joaat("a_m_y_juggalo_01")]="Juggalo"					MChar[joaat("ig_juanstrickler")]="Juanstrickler"		MChar[joaat("u_m_y_justin")]="Justin"
MChar[joaat("a_m_m_ktown_01")]="KTown01AMM"					MChar[joaat("a_m_o_ktown_01")]="KTown01AMO"				MChar[joaat("a_m_y_ktown_01")]="KTown01AMY"
MChar[joaat("a_m_y_ktown_02")]="KTown02AMY"					MChar[joaat("ig_lacey_jones_02")]="Lacey_jones2"		MChar[joaat("s_m_m_lathandy_01")]="Lathandy01SMM"
MChar[joaat("a_m_y_latino_01")]="Latino01AMY"				MChar[joaat("s_m_m_linecook")]="LineCookSMM"			MChar[joaat("s_m_m_lsmetro_01")]="LSMetro01SMM"
MChar[joaat("ig_malc")]="MalC"								MChar[joaat("a_m_m_malibu_01")]="Malibu01AMM"			MChar[joaat("u_m_y_mani")]="Mani"
MChar[joaat("ig_manuel")]="Manuel"							MChar[joaat("s_m_m_mariachi_01")]="Mariachi01SMM"		MChar[joaat("u_m_m_markfost")]="Markfost"
MChar[joaat("mp_m_meth_01")]="MethHead01AMY"				MChar[joaat("s_m_m_migrant_01")]="Migrant01SMM"			MChar[joaat("ig_milton")]="Milton"
MChar[joaat("ig_mjo")]="Mjo"								MChar[joaat("ig_mjo_02")]="Mjo2"						MChar[joaat("s_m_m_movprem_01")]="MovPrem01SMM"
MChar[joaat("a_m_y_musclbeac_01")]="MusclBeac01AMY"			MChar[joaat("a_m_y_musclbeac_02")]="MusclBeac02AMY"		MChar[joaat("ig_musician_00")]="Musician"
MChar[joaat("a_m_m_paparazzi_01")]="Paparazzi01AMM"			MChar[joaat("ig_paper")]="Paper"						MChar[joaat("s_m_m_paramedic_01")]="Paramedic01SMM"
MChar[joaat("u_m_y_party_01")]="Party01"					MChar[joaat("ig_party_promo")]="PartyPromo"				MChar[joaat("u_m_m_partytarget")]="PartyTarget"
MChar[joaat("s_m_y_pestcont_01")]="PestCont01SMY"			MChar[joaat("u_m_y_proldriver_01")]="PestContDriver"	MChar[joaat("hc_gunman")]="PestContGunman"
MChar[joaat("ig_pilot")]="Pilot"							MChar[joaat("s_m_m_pilot_01")]="Pilot01SMM"				MChar[joaat("s_m_y_pilot_01")]="Pilot01SMY"
MChar[joaat("s_m_m_pilot_02")]="Pilot02SMM"					MChar[joaat("a_m_m_polynesian_01")]="Polynesian01AMM"	MChar[joaat("a_m_y_polynesian_01")]="Polynesian01AMY"
MChar[joaat("ig_popov")]="Popov"							MChar[joaat("s_m_m_postal_01")]="Postal01SMM"			MChar[joaat("s_m_m_postal_02")]="Postal02SMM"
MChar[joaat("s_m_y_prismuscl_01")]="PrisMuscl01SMY"			MChar[joaat("u_m_y_prisoner_01")]="Prisoner01"			MChar[joaat("s_m_y_prisoner_01")]="Prisoner01SMY"
MChar[joaat("s_m_m_raceorg_01")]="RaceOrg"					MChar[joaat("ig_ramp_gang")]="RampGang"					MChar[joaat("ig_ramp_hic")]="RampHic"
MChar[joaat("a_m_y_runner_01")]="Runner01AMY"				MChar[joaat("a_m_y_runner_02")]="Runner02AMY"			MChar[joaat("a_m_m_rurmeth_01")]="RurMeth01AMM"
MChar[joaat("ig_russiandrunk")]="RussianDrunk"				MChar[joaat("a_m_m_salton_01")]="Salton01AMM"			MChar[joaat("a_m_o_salton_01")]="Salton01AMO"
MChar[joaat("a_m_y_salton_01")]="Salton01AMY"				MChar[joaat("a_m_m_salton_02")]="Salton02AMM"			MChar[joaat("a_m_m_salton_03")]="Salton03AMM"
MChar[joaat("a_m_m_salton_04")]="Salton04AMM"				MChar[joaat("mp_m_shopkeep_01")]="ShopKeep01"			MChar[joaat("s_m_y_shop_mask")]="ShopMaskSMY"
MChar[joaat("a_m_m_skater_01")]="Skater01AMM"				MChar[joaat("a_m_y_skater_01")]="Skater01AMY"			MChar[joaat("a_m_y_skater_02")]="Skater02AMY"
MChar[joaat("a_m_m_skidrow_01")]="SkidRow01AMM"				MChar[joaat("a_m_y_smartcaspat_01")]="SmartCaspatAMY"	MChar[joaat("a_m_m_socenlat_01")]="SoCenLat01AMM"
MChar[joaat("a_m_m_soucent_01")]="SouCent01AMM"				MChar[joaat("a_m_o_soucent_01")]="SouCent01AMO"			MChar[joaat("a_m_y_soucent_01")]="SouCent01AMY"
MChar[joaat("a_m_m_soucent_02")]="SouCent02AMM"				MChar[joaat("a_m_o_soucent_02")]="SouCent02AMO"			MChar[joaat("a_m_y_soucent_02")]="SouCent02AMY"
MChar[joaat("a_m_m_soucent_03")]="SouCent03AMM"				MChar[joaat("a_m_o_soucent_03")]="SouCent03AMO"			MChar[joaat("a_m_y_soucent_03")]="SouCent03AMY"
MChar[joaat("a_m_m_soucent_04")]="SouCent04AMM"				MChar[joaat("a_m_y_soucent_04")]="SouCent04AMY"			MChar[joaat("ig_soundeng_00")]="Soundeng"
MChar[joaat("u_m_m_spyactor")]="SpyActor"					MChar[joaat("u_m_y_staggrm_01")]="StagGrm01AMO"			MChar[joaat("a_m_y_stbla_01")]="StBla01AMY"
MChar[joaat("a_m_y_stbla_02")]="Stbla02AMY"					MChar[joaat("a_m_y_stlat_01")]="StLat01AMY"				MChar[joaat("a_m_m_stlat_02")]="StLat02AMM"
MChar[joaat("s_m_m_strperf_01")]="StrPerf01SMM"				MChar[joaat("s_m_m_strpreach_01")]="StrPreach01SMM"		MChar[joaat("g_m_y_strpunk_01")]="StrPunk01GMY"
MChar[joaat("g_m_y_strpunk_02")]="StrPunk02GMY"				MChar[joaat("s_m_m_strvend_01")]="StrVend01SMM"			MChar[joaat("s_m_y_strvend_01")]="StrVend01SMY"
MChar[joaat("s_m_m_studioassist_02")]="StudioAssistant"		MChar[joaat("a_m_m_studioparty_01")]="StudioParty1"		MChar[joaat("a_m_y_studioparty_01")]="StudioParty2"
MChar[joaat("s_m_m_studioprod_01")]="StudioProd"			MChar[joaat("s_m_m_studiosoueng_02")]="StudioSoueng"	MChar[joaat("a_m_y_stwhi_01")]="StWhi01AMY"
MChar[joaat("a_m_y_stwhi_02")]="StWhi02AMY"					MChar[joaat("a_m_y_sunbathe_01")]="SunBathe01AMY"		MChar[joaat("a_m_y_surfer_01")]="Surfer01AMY"
MChar[joaat("u_m_o_taphillbilly")]="TapHillBilly"			MChar[joaat("u_m_y_tattoo_01")]="Tattoo01AMO"			MChar[joaat("s_m_m_tattoo_01")]="Tattoo01SMM"
MChar[joaat("a_m_y_tattoocust_01")]="TattooCustomer"		MChar[joaat("a_m_m_tennis_01")]="Tennis01AMM"			MChar[joaat("ig_tenniscoach")]="TennisCoach"
MChar[joaat("ig_terry")]="Terry"							MChar[joaat("ig_tomepsilon")]="TomEpsilon"				MChar[joaat("a_m_m_tourist_01")]="Tourist01AMM"
MChar[joaat("a_m_m_tramp_01")]="Tramp01"					MChar[joaat("a_m_m_tramp_01")]="Tramp01AMM"				MChar[joaat("a_m_o_tramp_01")]="Tramp01AMO"
MChar[joaat("a_m_m_trampbeac_01")]="TrampBeac01AMM"			MChar[joaat("u_m_o_tramp_01")]="TrampBeac01UMO"			MChar[joaat("s_m_m_trucker_01")]="Trucker01SMM"
MChar[joaat("ig_dix")]="TylerDixon"							MChar[joaat("s_m_m_ups_01")]="UPS01SMM"					MChar[joaat("s_m_m_ups_02")]="UPS02SMM"
MChar[joaat("s_m_y_uscg_01")]="USCG01SMY"					MChar[joaat("s_m_y_valet_01")]="Valet01SMY"				MChar[joaat("ig_vernon")]="Vernon"
MChar[joaat("u_m_m_vince")]="Vince"							MChar[joaat("a_m_y_vinewood_01")]="VineWood01AMY"		MChar[joaat("a_m_y_vinewood_02")]="VineWood02AMY"
MChar[joaat("a_m_y_vinewood_03")]="Vinewood03AMY"			MChar[joaat("a_m_y_vinewood_04")]="Vinewood04AMY"		MChar[joaat("s_m_y_waiter_01")]="Waiter01SMY"
MChar[joaat("mp_m_weed_01")]="Weed"							MChar[joaat("ig_chengsr")]="WeiCheng"					MChar[joaat("u_m_m_willyfist")]="WillyFist"
MChar[joaat("s_m_y_winclean_01")]="WinClean01SMY"			MChar[joaat("s_m_y_xmech_01")]="XMech01SMY"				MChar[joaat("s_m_y_xmech_02")]="XMech02SMY"
MChar[joaat("s_m_y_xmech_02_mp")]="XMechMP02SMY"			MChar[joaat("a_m_y_yoga_01")]="Yoga01AMY"				MChar[joaat("ig_zimbor")]="Zimbor"
MChar[joaat("s_m_m_scientist_01")]="Scientist01SMM"		-- ----
MChar[joaat("a_m_o_acult_01")]="acult"						MChar[joaat("a_m_o_acult_02")]="acult2"					MChar[joaat("a_m_y_acult_01")]="acult3"
MChar[joaat("a_m_y_acult_02")]="acult4"						MChar[joaat("g_m_importexport_01")]="importexport"		MChar[joaat("g_m_m_casrn_01")]="casrn"
MChar[joaat("ig_avery")]="avery"							MChar[joaat("ig_gustavo")]="gustavo"					MChar[joaat("ig_huang")]="huang"
MChar[joaat("ig_oldrichguy")]="oldrich"						MChar[joaat("ig_ortega")]="ortega"						MChar[joaat("ig_prolsec_02")]="prolsec2"
MChar[joaat("ig_ramp_mex")]="rampmex"						MChar[joaat("ig_sacha")]="sacha"						MChar[joaat("ig_sss")]="sss"
MChar[joaat("ig_talcc")]="talcc"							MChar[joaat("ig_talmm")]="talmm"						MChar[joaat("ig_thornton")]="thorton"
MChar[joaat("a_m_m_mexcntry_01")]="mexcntry"				MChar[joaat("a_m_m_mlcrisis_01")]="mlcrisis"			MChar[joaat("a_m_m_prolhost_01")]="prolhost"
MChar[joaat("ig_tylerdix_02")]="TylerDix2"					MChar[joaat("ig_tylerdix")]="tylerDix"					MChar[joaat("ig_zimbor")]="Zimbor"
MChar[joaat("mp_g_m_pros_01")]="Pros1"						MChar[joaat("mp_headtargets")]="HeadTrgt"				MChar[joaat("mp_m_avongoon")]="AvonGoon"
MChar[joaat("mp_m_bogdangoon")]="BogDanGoon"				MChar[joaat("mp_m_cocaine_01")]="Coke"					MChar[joaat("mp_m_counterfeit_01")]="CounterF"
MChar[joaat("mp_m_forgery_01")]="ForG"						MChar[joaat("mp_m_marston_01")]="Marston"				MChar[joaat("mp_m_execpa_01")]="ExecPA"
MChar[joaat("mp_m_waremech_01")]="waremech"					MChar[joaat("mp_m_weapexp_01")]="weapexp"				MChar[joaat("mp_m_weapwork_01")]="weapwork"
MChar[joaat("mp_m_securoguard_01")]="SecuroGuard"			MChar[joaat("s_m_m_drugprocess_01")]="drugprocess"		MChar[joaat("s_m_m_fieldworker_01")]="fieldworker"
MChar[joaat("s_m_m_lifeinvad_01")]="lifeinvad"				MChar[joaat("s_m_y_casino_01")]="casino"				MChar[joaat("s_m_y_clubbar_01")]="clubbar"
MChar[joaat("s_m_y_devinsec_01")]="devinsec"				MChar[joaat("s_m_y_mime")]="mime"						MChar[joaat("s_m_y_waretech_01")]="waretech"
MChar[joaat("u_m_m_blane")]="blane"							MChar[joaat("u_m_m_curtis")]="curtis"					MChar[joaat("u_m_m_promourn_01")]="promourn"
MChar[joaat("u_m_m_rivalpap")]="rivalpap"					MChar[joaat("u_m_m_streetart_01")]="streetart"			MChar[joaat("u_m_y_caleb")]="caleb"
MChar[joaat("u_m_y_danceburl_01")]="danceburl"				MChar[joaat("u_m_y_dancelthr_01")]="dancelthr"			MChar[joaat("u_m_y_dancerave_01")]="dancerave"
MChar[joaat("u_m_y_fibmugger_01")]="fibmugger"				MChar[joaat("u_m_y_gabriel")]="gabriel"					MChar[joaat("u_m_y_ushi")]="ushi"
MChar[joaat("u_m_y_croupthief_01")]="croupthief"			MChar[joaat("u_m_y_smugmech_01")]="smugmech"			MChar[joaat("a_m_m_tranvest_01")]="tranvest"
MChar[joaat("a_m_m_tranvest_02")]="tranvest2"

FCutS[joaat("csb_abigail")]="AbigailCutscene"				FCutS[joaat("csb_agatha")]="AgathaCutscene"				FCutS[joaat("cs_amandatownley")]="AmandaTownleyCutscene"
FCutS[joaat("csb_anita")]="AnitaCutscene"					FCutS[joaat("cs_ashley")]="Ashley"						FCutS[joaat("csb_bryony")]="BrideCutscene"
FCutS[joaat("csb_bride")]="BryonyCutscene"					FCutS[joaat("cs_debra")]="DebraCutscene"				FCutS[joaat("cs_denise")]="DeniseCutscene"
FCutS[joaat("csb_georginacheng")]="GeorginaCutscene"		FCutS[joaat("cs_guadalope")]="GuadalopeCutscene"		FCutS[joaat("cs_gurk")]="GurkCutscene"
FCutS[joaat("csb_imani ")]="ImaniCutScene"					FCutS[joaat("csb_mimi ")]="MimiCutScene"				FCutS[joaat("csb_sessanta ")]="SessantaCutScene"
FCutS[joaat("cs_jewelass_01")]="JewelAss01Cutscene"			FCutS[joaat("cs_jewelass")]="JewelAssCutscene"			FCutS[joaat("cs_janet")]="JanetCutscene"
FCutS[joaat("cs_karen_daniels")]="KarenDanielsCutscene"		FCutS[joaat("cs_marnie")]="MarnieCutscene"				FCutS[joaat("cs_maryann")]="MaryannCutscene"
FCutS[joaat("csb_maude")]="MaudeCutscene"					FCutS[joaat("cs_michelle")]="MichelleCutScene"			FCutS[joaat("cs_molly")]="MollyCutscene"
FCutS[joaat("cs_movpremf_01")]="Movpremf_01"				FCutS[joaat("cs_mrs_thornhill")]="MrsThornhillCutscene"	FCutS[joaat("cs_mrsphillips")]="MrsPhillipsCutscene"
FCutS[joaat("csb_mrs_r")]="MrsRCutscene"					FCutS[joaat("cs_natalia")]="NataliaCutscene"			FCutS[joaat("csb_paige")]="PaigeCutscene"
FCutS[joaat("cs_patricia")]="PatriciaCutscene"				FCutS[joaat("cs_patricia_02")]="PatriciaCutscene2"		FCutS[joaat("csb_screen_writer")]="ScreenWriterCutscene"
FCutS[joaat("csb_stripper_01")]="Stripper01Cutscene"		FCutS[joaat("csb_stripper_02")]="Stripper02Cutscene"	FCutS[joaat("cs_tanisha")]="TanishaCutscene"
FCutS[joaat("csb_tonya")]="TonyaCutscene"					FCutS[joaat("cs_tracydisanto")]="TracyDisantoCutScene"	FCutS[joaat("csb_wendy")]="Wendy"

MCutS[joaat("csb_mp_agent14")]="Agent14Cutscene"			MCutS[joaat("csb_agent")]="AgentCutscene"				MCutS[joaat("csb_alan")]="AlanCutscene"
MCutS[joaat("csb_ary")]="AryCutscene"						MCutS[joaat("csb_ary_02")]="AryCutscene2"				MCutS[joaat("csb_avery")]="AveryCutscene"
MCutS[joaat("csb_avon")]="AvonCutscene"						MCutS[joaat("cs_andreas")]="AndreasCutscene"			MCutS[joaat("csb_anton")]="AntonCutscene"
MCutS[joaat("csb_money")]="AviSchwartzmanCuts"				MCutS[joaat("csb_avischwartzman_02")]="AviCutScene2"	MCutS[joaat("csb_ballas_leader")]="BallasLeaderCutscene"
MCutS[joaat("csb_ballasog")]="BallasOGCutscene"				MCutS[joaat("cs_bankman")]="BankmanCutscene"			MCutS[joaat("cs_barry")]="BarryCutscene"
MCutS[joaat("cs_beverly")]="BeverlyCutscene"				MCutS[joaat("csb_billionaire")]="BillonaireCutscene"	MCutS[joaat("cs_bradcadaver")]="BradCadaverCutscene"
MCutS[joaat("cs_brad")]="BradCutscene"						MCutS[joaat("csb_burgerdrug")]="BurgerDrugCutscene"		MCutS[joaat("csb_bogdan")]="BogdanCutscene"
MCutS[joaat("csb_brucie2")]="Brucie2Cutscene"				MCutS[joaat("csb_car3guy1")]="Car3Guy1Cutscene"			MCutS[joaat("csb_car3guy2")]="Car3Guy2Cutscene"
MCutS[joaat("cs_carbuyer")]="CarBuyerCutscene"				MCutS[joaat("cs_casey")]="CaseyCutscene"				MCutS[joaat("csb_celeb_01")]="CelebCutscene"
MCutS[joaat("csb_chef")]="ChefCutscene"						MCutS[joaat("csb_chef2")]="Chef2Cutscene"				MCutS[joaat("csb_chin_goon")]="ChinGoonCutscene"
MCutS[joaat("cs_clay")]="ClayCutscene"						MCutS[joaat("csb_cletus")]="CletusCutscene"				MCutS[joaat("a_m_y_gencaspat_01")]="ClubCust1Cutscene"
MCutS[joaat("a_m_y_gencaspat_02")]="ClubCust2Cutscene"		MCutS[joaat("a_m_y_gencaspat_03")]="ClubCust3Cutscene"	MCutS[joaat("a_m_y_gencaspat_04")]="ClubCust4Cutscene"
MCutS[joaat("cs_chrisformage")]="CrisFormageCutscene"		MCutS[joaat("csb_customer")]="CustomerCutscene"			MCutS[joaat("csb_cop")]="Cop"
MCutS[joaat("cs_dale")]="DaleCutscene"						MCutS[joaat("cs_davenorton")]="DaveNortonCutscene"		MCutS[joaat("cs_devin")]="DevinCutscene"
MCutS[joaat("csb_dix")]="TylerDixonCutscene"				MCutS[joaat("csb_djblamadon")]="DJBlamadon"				MCutS[joaat("csb_isldj_00")]="DJ0"
MCutS[joaat("csb_isldj_01")]="DJ1"							MCutS[joaat("csb_isldj_02")]="DJ2"						MCutS[joaat("csb_isldj_03")]="DJ3"
MCutS[joaat("csb_isldj_04")]="DJ4"							MCutS[joaat("cs_dom")]="DomCutscene"					MCutS[joaat("cs_dreyfuss")]="DreyfussCutscene"
MCutS[joaat("cs_drfriedlander")]="DrFriedlanderCutscene"	MCutS[joaat("csb_drugdealer")]="DrugDealerCutscene"		MCutS[joaat("csb_englishdave")]="EnglishDave"
MCutS[joaat("csb_englishdave_02")]="EngDave2"				MCutS[joaat("cs_fabien")]="FabienCutscene"				MCutS[joaat("cs_fbisuit_01")]="FBISuitCutS"
MCutS[joaat("cs_floyd")]="FloydCutscene"					MCutS[joaat("csb_fos_rep")]="FosRepCutscene"			MCutS[joaat("csb_g")]="GCutscene"
MCutS[joaat("csb_golfer_a")]="GolferACutS"					MCutS[joaat("csb_golfer_b")]="GolferBCutS"				MCutS[joaat("csb_gustavo")]="GustavoCutscene"
MCutS[joaat("csb_groom")]="GroomCutscene"					MCutS[joaat("csb_grove_str_dlr")]="GroveStrDlrCutscene"	MCutS[joaat("csb_hao")]="HaoCutscene"
MCutS[joaat("csb_hao_02")]="HaoCutscene2"					MCutS[joaat("csb_huang")]="HuangCutscene"				MCutS[joaat("csb_hugh")]="HughCutscene"
MCutS[joaat("cs_hunter")]="HunterCutscene"					MCutS[joaat("csb_imran")]="ImranCutscene"				MCutS[joaat("csb_jackhowitzer")]="JackHowitzerCutscene"
MCutS[joaat("csb_janitor")]="JanitorCutscene"				MCutS[joaat("cs_jimmyboston")]="JimmyBostonCutscene"	MCutS[joaat("cs_jimmydisanto")]="JimmyDisantoCutscene"
MCutS[joaat("cs_jimmydisanto2")]="JimmyDisanto2Cutscene"	MCutS[joaat("csb_jio_02")]="Jio2Cutscene"				MCutS[joaat("cs_joeminuteman")]="JoeMinutemanCutscene"
MCutS[joaat("cs_johnnyklebitz")]="JohnnyKlebitzCutscene"	MCutS[joaat("csb_johnny_guns")]="JohnnyGunsCutscene"	MCutS[joaat("cs_josef")]="JosefCutscene"
MCutS[joaat("cs_josh")]="JoshCutscene"						MCutS[joaat("csb_juanstrickler")]="JuanCutscene"		MCutS[joaat("cs_lamardavis")]="LamarDavisCutscene"
MCutS[joaat("cs_lamardavis_02")]="LamarDavisCutscene2"		MCutS[joaat("cs_lazlow")]="LazlowCutscene"				MCutS[joaat("cs_lazlow_2")]="LazlowCutscene2"
MCutS[joaat("cs_lestercrest")]="LesterCrestCutscene"		MCutS[joaat("cs_lestercrest_2")]="LesterCrestCutscene2"	MCutS[joaat("cs_lestercrest_3")]="LesterCrestCutscene3"
MCutS[joaat("cs_lifeinvad_01")]="LifeInvad01Cutscene"		MCutS[joaat("cs_magenta")]="MagentaCutscene"			MCutS[joaat("csb_ramp_marine")]="MarineCutS"
MCutS[joaat("csb_mweather")]="MweatherCutS"					MCutS[joaat("cs_manuel")]="ManuelCutscene"				MCutS[joaat("csb_martinmadrazo")]="MartinMadrazoCutscene"
MCutS[joaat("csb_miguelmadrazo")]="MiguelCutscene"			MCutS[joaat("cs_milton")]="MiltonCutscene"				MCutS[joaat("csb_mjo")]="MjoCutscene"
MCutS[joaat("csb_mjo_02")]="MjoCutscene2"					MCutS[joaat("csb_moodyman_02")]="MoodymanCutscene"		MCutS[joaat("cs_movpremmale")]="MoviePremMaleCutscene"
MCutS[joaat("cs_mrk")]="MrKCutscene"						MCutS[joaat("csb_musician_00")]="MusicianCutscene"		MCutS[joaat("cs_nervousron")]="NervousRonCutscene"
MCutS[joaat("cs_nigel")]="NigelCutscene"					MCutS[joaat("cs_old_man1a")]="OldMan1aCutscene"			MCutS[joaat("cs_old_man2")]="OldMan2Cutscene"
MCutS[joaat("cs_omega")]="OmegaCutscene"					MCutS[joaat("cs_orleans")]="OrleansCutscene"			MCutS[joaat("csb_ortega")]="OrtegaCutScene"
MCutS[joaat("csb_oscar")]="OscarCutscene"					MCutS[joaat("cs_paper")]="PaperCutscene"				MCutS[joaat("csb_party_promo")]="PartyPromoCutscene"
MCutS[joaat("csb_helmsmanpavel")]="PavelCutscene"			MCutS[joaat("csb_popov")]="PopovCutscene"				MCutS[joaat("csb_porndudes")]="PornDudesCutscene"
MCutS[joaat("cs_priest")]="PriestCutscene"					MCutS[joaat("csb_prologuedriver")]="ProlDriverCutscene"	MCutS[joaat("csb_prolsec")]="PrologueSec01Cutscene"
MCutS[joaat("cs_prolsec_02")]="PrologueSec02Cutscene"		MCutS[joaat("csb_ramp_gang")]="RampGangCutscene"		MCutS[joaat("csb_ramp_hic")]="RampHicCutscene"
MCutS[joaat("csb_ramp_hipster")]="RampHipsterCutscene"		MCutS[joaat("csb_ramp_mex")]="RampMexCutscene"			MCutS[joaat("csb_rashcosvki")]="RashkovskyCutscene"
MCutS[joaat("csb_req_officer")]="ReqOfficerCutscene"		MCutS[joaat("csb_roccopelosi")]="RoccoPelosiCutscene"	MCutS[joaat("cs_russiandrunk")]="RussianDrunkCutscene"
MCutS[joaat("csb_security_a")]="SecurityCutscene"			MCutS[joaat("csb_screen_writer")]="ScrnWriterCutscene"	MCutS[joaat("cs_siemonyetarian")]="SiemonYetarianCutscene"
MCutS[joaat("csb_sol")]="SolCutscene"						MCutS[joaat("cs_solomon")]="SolomonCutscene"			MCutS[joaat("csb_soundeng_00")]="SoundengCutscene"
MCutS[joaat("csb_sss")]="SSSCutScene"						MCutS[joaat("cs_stevehains")]="SteveHainsCutscene"		MCutS[joaat("cs_stretch")]="StretchCutscene"
MCutS[joaat("cs_taocheng")]="TaoChengCutscene"				MCutS[joaat("csb_talcc")]="TalccCutscene"				MCutS[joaat("csb_talmm")]="TalmCutscene"
MCutS[joaat("csb_thornton")]="ThortonCutscene"				MCutS[joaat("cs_taocheng2")]="TaoChengCutscene2"		MCutS[joaat("cs_taostranslator")]="TaosTranslatorCutscene"
MCutS[joaat("cs_taostranslator2")]="TaosTranslatorCutS2"	MCutS[joaat("cs_tenniscoach")]="TennisCoachCutscene"	MCutS[joaat("cs_terry")]="TerryCutscene"
MCutS[joaat("cs_tom")]="TomCutscene"						MCutS[joaat("csb_tomcasino")]="TomCasinoCutscene"		MCutS[joaat("cs_tomepsilon")]="TomEpsilonCutscene"
MCutS[joaat("csb_tonyprince")]="TonyPrinceCutscene"			MCutS[joaat("csb_reporter")]="ReporterCutscene"			MCutS[joaat("csb_trafficwarden")]="TrafficWardenCutscene"
MCutS[joaat("csb_undercover")]="UndercoverCopCutscene"		MCutS[joaat("csb_vagos_leader")]="VagosLeaderCutscene"	MCutS[joaat("csb_vagspeak")]="VagosSpeakCutscene"
MCutS[joaat("csb_vernon")]="VernonCutscene"					MCutS[joaat("csb_vincent")]="VinCentCutscene"			MCutS[joaat("csb_vincent_2")]="VinCentCutscene2"
MCutS[joaat("cs_wade")]="WadeCutscene"						MCutS[joaat("cs_chengsr")]="WeiChengCutscene"			MCutS[joaat("cs_zimbor")]="ZimborCutscene"
MCutS[joaat("csb_jio")]="JioCutscene"

FGang[joaat("g_f_y_ballas_01")]="Ballas01GFY"				FGang[joaat("a_f_m_downtown_01")]="DownTown01AFM"		FGang[joaat("a_m_y_downtown_01")]="DownTown01AMY"
FGang[joaat("g_f_y_families_01")]="Families1"				FGang[joaat("g_f_y_lost_01")]="Lost01GFY"				FGang[joaat("g_f_y_vagos_01")]="Vagos01GFY"

MGang[joaat("g_m_m_armboss_01")]="ArmBoss01GMM"				MGang[joaat("g_m_m_armgoon_01")]="ArmGoon01GMM"			MGang[joaat("g_m_y_armgoon_02")]="ArmGoon02GMY"
MGang[joaat("g_m_m_armlieut_01")]="ArmLieut01GMM"			MGang[joaat("mp_s_m_armoured_01")]="Armoured01"			MGang[joaat("s_m_m_armoured_01")]="Armoured01SMM"
MGang[joaat("s_m_m_armoured_02")]="Armoured02SMM"			MGang[joaat("s_m_y_armymech_01")]="ArmyMech01SMY"		MGang[joaat("g_m_y_ballaeast_01")]="BallaEast01GMY"
MGang[joaat("ig_ballas_leader")]="BallasLeader"				MGang[joaat("g_m_y_ballaorig_01")]="BallaOrig01GMY"		MGang[joaat("ig_ballasog")]="BallasOG"
MGang[joaat("g_m_y_ballasout_01")]="BallaSout01GMY"			MGang[joaat("g_m_m_cartelguards_01")]="Cartelguards1"	MGang[joaat("g_m_m_cartelguards_02")]="Cartelguards2"
MGang[joaat("g_m_m_chiboss_01")]="ChiBoss01GMM"				MGang[joaat("g_m_m_chicold_01")]="ChiCold01GMM"			MGang[joaat("g_m_m_chigoon_01")]="ChiGoon01GMM"
MGang[joaat("g_m_m_chigoon_02")]="ChiGoon02GMM"				MGang[joaat("g_m_m_goons_01")]="Goons"					MGang[joaat("ig_hunter")]="Hunter"
MGang[joaat("g_m_y_korean_01")]="Korean1"					MGang[joaat("g_m_y_korean_02")]="Korean2"				MGang[joaat("g_m_y_korlieut_01")]="KoreanLieut"
MGang[joaat("g_m_m_korboss_01")]="KorBoss01GMM"				MGang[joaat("g_m_y_lost_01")]="Lost01GMY"				MGang[joaat("g_m_y_lost_02")]="Lost02GMY"
MGang[joaat("g_m_y_lost_03")]="Lost03GMY"					MGang[joaat("a_m_y_methhead_01")]="MethHead01AMY"		MGang[joaat("g_m_m_mexboss_01")]="MexBoss01GMM"
MGang[joaat("g_m_m_mexboss_02")]="MexBoss02GMM"				MGang[joaat("a_m_m_mexcntry_01")]="MexCntry01AMM"		MGang[joaat("g_m_y_mexgang_01")]="MexGang01GMY"
MGang[joaat("g_m_y_mexgoon_01")]="MexGoon01GMY"				MGang[joaat("g_m_y_mexgoon_02")]="MexGoon02GMY"			MGang[joaat("g_m_y_mexgoon_03")]="MexGoon03GMY"
MGang[joaat("a_m_m_mexlabor_01")]="MexLabor01AMM"			MGang[joaat("a_m_y_mexthug_01")]="Mexthug01AMY"			MGang[joaat("u_m_y_militarybum")]="MilitaryBum"
MGang[joaat("a_m_y_motox_01")]="Motox01AMY"					MGang[joaat("a_m_y_motox_02")]="Motox02AMY"				MGang[joaat("a_m_m_og_boss_01")]="OGBoss01AMM"
MGang[joaat("ig_old_man1a")]="OldMan1A"						MGang[joaat("ig_old_man2")]="OldMan2"					MGang[joaat("ig_omega")]="Omega"
MGang[joaat("ig_oneil")]="Oneil"							MGang[joaat("g_m_y_pologoon_01")]="PoloGoon"			MGang[joaat("g_m_y_pologoon_02")]="PoloGoon2"
MGang[joaat("g_m_m_prisoners_01")]="Prisoners"				MGang[joaat("u_m_y_paparazzi")]="RivalPaparazzi"		MGang[joaat("a_m_y_roadcyc_01")]="RoadCyc01AMY"
MGang[joaat("s_m_y_robber_01")]="Robber01SMY"				MGang[joaat("ig_roccopelosi")]="RoccoPelosi"			MGang[joaat("g_m_y_salvaboss_01")]="SalvaBoss01GMY"
MGang[joaat("g_m_y_salvagoon_01")]="SalvaGoon01GMY"			MGang[joaat("g_m_y_salvagoon_02")]="SalvaGoon02GMY"		MGang[joaat("g_m_y_salvagoon_03")]="SalvaGoon03GMY"
MGang[joaat("u_m_y_sbike")]="SBikeAMO"						MGang[joaat("g_m_m_slasher_01")]="Slasher"				MGang[joaat("ig_vagos_leader")]="VagosLeader"
MGang[joaat("mp_m_g_vagfun_01")]="VagosFun01"				MGang[joaat("ig_vagspeak")]="VagosSpeak"				MGang[joaat("a_m_y_vindouche_01")]="VinDouche01AMY"

LAW[joaat("s_f_y_sheriff_01")]="Sheriff01SFY"				LAW[joaat("s_m_y_sheriff_01")]="Sheriff01SMY"			LAW[joaat("s_m_y_blackops_01")]="BlackOps01SMY"
LAW[joaat("s_m_y_blackops_02")]="BlackOps02SMY"				LAW[joaat("s_m_y_blackops_03")]="BlackOps03SMY"			LAW[joaat("ig_casey")]="Casey"
LAW[joaat("s_m_m_ciasec_01")]="CIASec01SMM"					LAW[joaat("s_m_y_cop_01")]="Cop01SMY"					LAW[joaat("s_f_y_cop_01")]="Cop01SFY"
LAW[joaat("csb_cop")]="CopCutscene"							LAW[joaat("ig_fbisuit_01")]="FBISuit01"					LAW[joaat("a_f_y_femaleagent")]="FemaleAgent"
LAW[joaat("u_m_m_fibarchitect")]="FIBArchitect"				LAW[joaat("u_m_y_fibmugger_01")]="FIBMugger01"			LAW[joaat("s_m_m_fiboffice_01")]="FIBOffice01SMM"
LAW[joaat("s_m_m_fiboffice_02")]="FIBOffice02SMM"			LAW[joaat("mp_m_fibsec_01")]="FIBSec01"					LAW[joaat("s_m_m_fibsec_01")]="FIBSec01SMM"
LAW[joaat("s_m_m_highsec_01")]="HighSec01SMM"				LAW[joaat("s_m_m_highsec_02")]="HighSec02SMM"			LAW[joaat("s_m_m_highsec_03")]="HighSec03SMM"
LAW[joaat("s_m_m_highsec_04")]="HighSec04SMM"				LAW[joaat("s_m_m_highsec_05")]="HighSec05SMM"			LAW[joaat("s_m_y_hwaycop_01")]="HWayCop01SMY"
LAW[joaat("s_m_m_marine_01")]="Marine01SMM"					LAW[joaat("s_m_y_marine_01")]="Marine01SMY"				LAW[joaat("s_m_m_marine_02")]="Marine02SMM"
LAW[joaat("s_m_y_marine_02")]="Marine02SMY"					LAW[joaat("s_m_y_marine_03")]="Marine03SMY"				LAW[joaat("csb_mweather")]="MerryWeatherCutscene"
LAW[joaat("mp_g_m_pros_01")]="MPros01"						LAW[joaat("s_m_m_prisguard_01")]="PrisGuard01SMM"		LAW[joaat("s_f_y_ranger_01")]="Ranger01SFY"
LAW[joaat("s_m_y_ranger_01")]="Ranger01SMY"					LAW[joaat("ig_req_officer")]="ReqOfficer"				LAW[joaat("ig_security_a")]="Security"
LAW[joaat("s_m_m_security_01")]="Security01SMM"				LAW[joaat("s_m_m_snowcop_01")]="SnowCop01SMM"			LAW[joaat("s_m_y_swat_01")]="SWAT01SMY"
LAW[joaat("csb_undercover")]="UndercoverCopCutscene"	-- ----
LAW[joaat("ig_trafficwarden")]="trafficWarden"				LAW[joaat("mp_m_exarmy_01")]="ExArmy"					LAW[joaat("mp_m_fibsec_01")]="FibSec1"
LAW[joaat("mp_s_m_armoured_01")]="armoured"					LAW[joaat("s_m_m_armoured_01")]="armoured2"				LAW[joaat("s_m_m_armoured_02")]="armoured3"
LAW[joaat("s_m_m_ciasec_01")]="ciasec"						LAW[joaat("s_m_m_fiboffice_01")]="fiboffice"			LAW[joaat("s_m_m_fiboffice_02")]="fiboffice2"
LAW[joaat("s_m_m_fibsec_01")]="fibsec"						LAW[joaat("s_m_m_highsec_01")]="highsec"				LAW[joaat("s_m_m_highsec_02")]="highsec2"
LAW[joaat("s_m_m_highsec_03")]="highsec3"					LAW[joaat("s_m_m_highsec_04")]="highsec4"				LAW[joaat("s_m_m_marine_01")]="marine1"
LAW[joaat("s_m_m_marine_02")]="marine2"						LAW[joaat("s_m_m_prisguard_01")]="prisguard"			LAW[joaat("s_m_m_security_01")]="security"
LAW[joaat("s_m_m_snowcop_01")]="snowcop"					LAW[joaat("s_m_y_armymech_01")]="armymech"				LAW[joaat("s_m_y_blackops_01")]="blackops"
LAW[joaat("s_m_y_blackops_02")]="blackops2"					LAW[joaat("s_m_y_blackops_03")]="blackops3"				LAW[joaat("s_m_y_hwaycop_01")]="hwaycop"
LAW[joaat("s_m_y_marine_01")]="marine1"						LAW[joaat("s_m_y_marine_02")]="marine2"					LAW[joaat("s_m_y_marine_03")]="marine3"
LAW[joaat("s_m_y_ranger_01")]="ranger"						LAW[joaat("s_m_y_sheriff_01")]="sheriff"				LAW[joaat("s_m_y_swat_01")]="swat"
LAW[joaat("s_m_y_westsec_01")]="westsec"					LAW[joaat("s_m_y_westsec_02")]="westsec2"				LAW[joaat("u_m_m_fibarchitect")]="fibarchitect"

Other[joaat("slod_human")]="human"							Other[joaat("slod_large_quadped")]="large_quadped"		Other[joaat("slod_small_quadped")]="small_quadped"

ShpShft:add_array_item("Turn Back Into", MP, function() if Sx==1 then return joaat("mp_m_freemode_01") else return joaat("mp_f_freemode_01") end end, function(Mp)
	if Mp==joaat("mp_f_freemode_01") then Sx=2 else Sx=1 end set_model_hash(Mp) localplayer:set_godmode(false) end)
ShpShft:add_array_item("Become Animal", ANM, function() if Ani then return Ani else return joaat("a_c_chop") end end, function(Anm) Ani=Anm set_model_hash(Anm) localplayer:set_godmode(true) end)
ShpShft:add_array_item("Become ....", CosP, function() if Cos then return Cos else return joaat("ig_orleans") end end, function(Rnd) Cos=Rnd set_model_hash(Rnd) end)
ShpShft:add_array_item("Become Bird", BRD, function() if Birdy then return Birdy else return joaat("a_c_chickenhawk") end end, function(Brd) Birdy=Brd set_model_hash(Brd) end)
ShpShft:add_array_item("Become Sea creature", SCRe, function() if Sea then return Sea else
	return joaat("a_c_dolphin") end end, function(SAn) Sea=SAn set_model_hash(SAn) localplayer:set_godmode(true) end)
ShpShft:add_array_item("Become Story Female", FCHarSt, function() if FemSt then return FemSt else return joaat("ig_amandatownley") end end, function(FeSt) FemSt=FeSt set_model_hash(FeSt) end)
ShpShft:add_array_item("Become Story Male", MCHarSt, function() if mSt then return mSt else return joaat("player_zero") end end, function(MSto) mSt=MSto set_model_hash(MSto) end)
ShpShft:add_array_item("Become Female Ped", FChar, function() if FeC then return FeC else return joaat("a_f_y_fitness_01") end end, function(FCh) FeC=FCh set_model_hash(FCh) end)
ShpShft:add_array_item("Become Male Ped", MChar, function() if MaC then return MaC else return joaat("ig_chengsr") end end, function(MCh) MaC=MCh set_model_hash(MCh) end)
ShpShft:add_array_item("Female(CutScene)", FCutS, function() if FCu then return FCu else return joaat("cs_tracydisanto") end end, function(FCt) FCu=FCt set_model_hash(FCt) end)
ShpShft:add_array_item("Male(CutScene)", MCutS, function() if MCu then return MCu else return joaat("csb_miguelmadrazo") end end, function(MCt) MCu=MCt set_model_hash(MCt) end)
ShpShft:add_array_item("Female(GangMem)", FGang, function() if FGn then return FGn else return joaat("g_f_y_families_01") end end, function(FGa) FGn=FGa set_model_hash(FGa) end)
ShpShft:add_array_item("Male(GangMem)", MGang, function() if MGn then return MGn else return joaat("g_m_m_mexboss_02") end end, function(MGa) MGn=MGa set_model_hash(MGa) end)
ShpShft:add_array_item("Become Law enforcer", LAW, function() if Law then return Law else return joaat("mp_m_fibsec_01") end end, function(Lw) Law=Lw set_model_hash(Lw) end)
ShpShft:add_array_item("Others", Other, function() if Oth then return Oth else return joaat("slod_human") end end, function(oth) Oth=oth set_model_hash(oth) end)